ymax: 255
ymin: 45
dateformat: ddMMyy
groups:
  garten: # <- use this as the permission e.g. simpleplayerregions.group.garten
    max-region-per-world: 1
    max-region-side-length: 100
  default: # <- this is the default for all players without a specific group
    max-region-per-world: 0
    max-region-side-length: 100
lang:
  regionformat: %playername%_%date%
  no-selection: &cPlease select an area first!
  unsupported-selectiontype: &cThe selection type %type% is not supported by WorldGuard!
  world-not-enabled: &cWorldGuard is not enabled in the world %world%!
  overlapping-regions: &cSorry. There is already a region defined here!
  too-many-regions: &cYou already reached the maximum ammount of regions you can define in the world %world%!
  selection-to-big: &cThis region would be too big! Make it smaller.